language: python
python:
  - "2.7"

install:
  # Install Sublime Text 2
  - wget "http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.2.tar.bz2"
  - tar xvf "Sublime Text 2.0.2.tar.bz2"
  - sudo cp -rv $PWD"/Sublime Text 2" /usr/lib/sublime-text-2
  - sudo ln -s /usr/lib/sublime-text-2/sublime_text /usr/bin/sublime_text

  # List Sublime Text info for debugging
  - ls -la /usr/lib/sublime-text-2/sublime_text
  - ls -la /usr/bin/sublime_text
  - $PWD"/Sublime Text 2/sublime_text" --version
  - /usr/lib/sublime-text-2/sublime_text --version
  - /usr/bin/sublime_text --version
  - sublime_text --version

  # Install `sublime_plugin_tests`
  - python setup.py install

script:
  - ./test.sh

notifications:
  email: false
