language: python
python:
  - "2.7"

install:
  # Install Sublime Text 2
  - wget "http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.2.tar.bz2"
  - tar xzf Sublime%20Text%202.0.2.tar.bz2
  - sudo cp -r $PWD"/Sublime Text 2"/usr/lib/sublime-text-2/
  - sudo ln -s /usr/lib/sublime-text-2/sublime_text /usr/bin/sublime_text

  # Install `sublime_plugin_tests`
  - python setup.py install

script:
  - ./test.sh

notifications:
  email: false
