language: python
python:
  - "2.7"

install:
  # Install Sublime Text 2
  # http://askubuntu.com/questions/172698/how-do-i-install-sublime-text-2
  - sudo add-apt-repository ppa:webupd8team/sublime-text-2 -y
  - sudo apt-get update
  - sudo apt-get install sublime-text -y

  # List Sublime Text info for debugging
  - subl --version

  # Install `sublime_plugin_tests`
  - python setup.py install

script:
  - ./test.sh

notifications:
  email: false
