language: python
python:
  - "2.7"

install:
  # Install Sublime Text 2
  - sudo add-apt-repository ppa:webupd8team/sublime-text-2
  - sudo apt-get update
  - sudo apt-get install sublime-text

  # List Sublime Text info for debugging
  - sublime_text --version

  # Install `sublime_plugin_tests`
  - python setup.py install

script:
  - ./test.sh

notifications:
  email: false
